services:

  firstms:
    container_name: FirstMs
    image: first-microservice
    build:
      context: .
    ports:
      - "${FIRST_HOST_PORT:-8082}:${FIRST_PORT:-8081}"
    environment:
        - FIRST_PORT=${FIRST_PORT}
        - FIRST_HOST_PORT=${FIRST_HOST_PORT}
        - SECOND_PORT=${SECOND_PORT}
        - FIRST_DB_USER=${FIRST_DB_USER}
        - FIRST_DB_PASSWORD=${FIRST_DB_PASSWORD}
        - FIRST_DB=${FIRST_DB}
        - FIRST_DB_PORT=${FIRST_DB_PORT}
        - KAFKA_INSIDE_PORT=${KAFKA_INSIDE_PORT}
    depends_on:
      - firstdb
      - zookeeper
      - kafka
      - redis
    networks:
      - ms-network

  firstdb:
    image: postgres:16.2
    container_name: FirstDb
    environment:
      POSTGRES_USER: ${FIRST_DB_USER}
      POSTGRES_PASSWORD: ${FIRST_DB_PASSWORD}
      POSTGRES_DB: ${FIRST_DB}
    ports:
      - "${FIRST_DB_PORT}:${FIRST_DB_PORT}"
    command: ["postgres", "-p", "${FIRST_DB_PORT}"]
    networks:
      - ms-network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_PORT}"
    networks:
      - ms-network

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    ports:
      - "${KAFKA_PORT}:${KAFKA_PORT}"
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT}
      KAFKA_LISTENERS: INSIDE://kafka:${KAFKA_INSIDE_PORT},PLAINTEXT://localhost:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_PORT: ${KAFKA_PORT}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - ms-network

  redis:
    image: redis:7.4.0
    container_name: redis
#    environment:
#      - REDIS_PASSWORD=${REDIS_PASSWORD}
#      - REDIS_USER=${REDIS_USER}
#      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - ms-network

networks:
  ms-network:
    name: ms-network
    driver: bridge