FROM openjdk:17-jdk-alpine3.14
ARG JAR_FILE=target/*.jar

ENV FIRST_PORT="${FIRST_PORT}"
ENV FIRST_HOST_PORT="${FIRST_HOST_PORT}"

ENV SECOND_PORT="${SECOND_PORT}"

ENV FIRST_DB_USER="${FIRST_DB_USER}"
ENV FIRST_DB_PASSWORD="${FIRST_DB_PASSWORD}"
ENV FIRST_DB="${FIRST_DB}"
ENV FIRST_DB_PORT="${FIRST_DB_PORT}"

ENV KAFKA_INSIDE_PORT="${KAFKA_INSIDE_PORT}"

COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar", "--spring.profiles.active=dev"]
