server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/first_db
    username: first_db_user
    password: first_db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cluster:
  secondms:
    port: 8081
    host: localhost
    url: /api/v1/second

logging:
  level:
    root: INFO
    com.velb: INFO
