server:
  port: ${FIRST_PORT:8081}

spring:
  datasource:
    url: jdbc:postgresql://firstdb:${FIRST_DB_PORT}/${FIRST_DB}
    username: ${FIRST_DB_USER}
    password: ${FIRST_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

cluster:
  secondms:
    url: http://secondms:${SECOND_PORT:8087}//api/v1/second
